// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEH2ADqsESH9RMXNEzTJckYRwmuj4kcfA',
    appId: '1:961160655128:web:c1ed8a5f6e1b81f58dae6d',
    messagingSenderId: '961160655128',
    projectId: 'alfairouzz1notification-5bf2f',
    authDomain: 'alfairouzz1notification-5bf2f.firebaseapp.com',
    storageBucket: 'alfairouzz1notification-5bf2f.appspot.com',
    measurementId: 'G-WJ73B114SR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsO_g0G0yY-swumu2TzSBDQIz1Scq71Xw',
    appId: '1:961160655128:android:d499fdcdd1ffb52b8dae6d',
    messagingSenderId: '961160655128',
    projectId: 'alfairouzz1notification-5bf2f',
    storageBucket: 'alfairouzz1notification-5bf2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCePjCEz7zumo4F_3L20pGE4QdsD2JFBg',
    appId: '1:961160655128:ios:e064b7e009bd01e48dae6d',
    messagingSenderId: '961160655128',
    projectId: 'alfairouzz1notification-5bf2f',
    storageBucket: 'alfairouzz1notification-5bf2f.appspot.com',
    iosBundleId: 'com.example.alfairouzz1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCePjCEz7zumo4F_3L20pGE4QdsD2JFBg',
    appId: '1:961160655128:ios:e064b7e009bd01e48dae6d',
    messagingSenderId: '961160655128',
    projectId: 'alfairouzz1notification-5bf2f',
    storageBucket: 'alfairouzz1notification-5bf2f.appspot.com',
    iosBundleId: 'com.example.alfairouzz1',
  );
}
